<?php
if ($country == 'Afghanistan') $country ='AF';
if ($country == 'Albania') $country ='AL';
if ($country == 'Algeria') $country ='DZ';
if ($country == 'American') $country ='Samoa';
if ($country == 'Andorra') $country ='AD';
if ($country == 'Angola') $country ='AO';
if ($country == 'Anguilla') $country ='AI';
if ($country == 'Antarctica') $country ='AQ';
if ($country == 'Antigua and Barbuda') $country ='AG';
if ($country == 'Argentina') $country ='AR';
if ($country == 'Armenia') $country ='AM';
if ($country == 'Aruba') $country ='AW';
if ($country == 'Australia') $country ='AU';
if ($country == 'Austria') $country ='AT';
if ($country == 'Azerbaijan') $country ='AZ';
if ($country == 'Bahamas') $country ='BS';
if ($country == 'Bahrain') $country ='BH';
if ($country == 'Bangladesh') $country ='BD';
if ($country == 'Barbados') $country ='BB';
if ($country == 'Belarus') $country ='BY';
if ($country == 'Belgium') $country ='BE';
if ($country == 'Belize') $country ='BZ';
if ($country == 'Benin') $country ='BJ';
if ($country == 'Bermuda') $country ='BM';
if ($country == 'Bhutan') $country ='BT';
if ($country == 'Bolivia') $country ='BO';
if ($country == 'Bosnia and Herzegovina') $country ='BA';
if ($country == 'Botswana') $country ='BW';
if ($country == 'Brazil') $country ='BR';
if ($country == 'British Virgin Islands') $country ='VI';
if ($country == 'Brunei Darussalam') $country ='BN';
if ($country == 'Bulgaria') $country ='BG';
if ($country == 'Burkina Faso') $country ='BF';
if ($country == 'Burundi') $country ='BI';
if ($country == 'Cambodia') $country ='KH';
if ($country == 'Cameroon') $country ='CM';
if ($country == 'Canada') $country ='CA';
if ($country == 'Cape Verde') $country ='CV';
if ($country == 'Cayman Islands') $country ='KY';
if ($country == 'Central African Republic') $country ='CF';
if ($country == 'Chad') $country ='TD';
if ($country == 'Chile') $country ='CL';
if ($country == 'China') $country ='CN';
if ($country == 'Christmas Island') $country ='CX';
if ($country == 'Cocos (Keeling) Islands') $country ='CC';
if ($country == 'Colombia') $country ='CO';
if ($country == 'Comoros') $country ='KM';
if ($country == 'Congo Dem. Rep of the') $country ='CD';
if ($country == 'Congo, Republic of') $country ='CG';
if ($country == 'Cook Islands') $country ='CK';
if ($country == 'Costa Rica') $country ='CR';
if ($country == 'Cote D\'Ivoire') $country ='CI';
if ($country == 'Croatia/Hrvatska') $country ='HR';
if ($country == 'Cuba') $country ='CU';
if ($country == 'Cyprus') $country ='CY';
if ($country == 'Czech Republic') $country ='CZ';
if ($country == 'Denmark') $country ='DK';
if ($country == 'Djibouti') $country ='DJ';
if ($country == 'Dominica') $country ='DM';
if ($country == 'Dominican Republic') $country ='DO';
if ($country == 'Ecuador') $country ='EC';
if ($country == 'Egypt') $country ='EG';
if ($country == 'El Salvador') $country ='SV';
if ($country == 'Equatorial Guinea') $country ='GQ';
if ($country == 'Eritrea') $country ='ER';
if ($country == 'Estonia') $country ='EE';
if ($country == 'Ethiopia') $country ='ET';
if ($country == 'Falkland Islands (Malvinas)') $country ='FK';
if ($country == 'Faroe Islands') $country ='FO';
if ($country == 'Fiji') $country ='FJ';
if ($country == 'Finland') $country ='FI';
if ($country == 'France') $country ='FR';
if ($country == 'French Guiana') $country ='GF';
if ($country == 'French Polynesia') $country ='PF';
if ($country == 'French Southern Territories') $country ='TF';
if ($country == 'Gabon') $country ='GA';
if ($country == 'Gambia') $country ='GM';
if ($country == 'Georgia') $country ='GE';
if ($country == 'Germany') $country ='DE';
if ($country == 'Ghana') $country ='GH';
if ($country == 'Gibraltar') $country ='GI';
if ($country == 'Greece') $country ='GR';
if ($country == 'Greenland') $country ='GL';
if ($country == 'Grenada') $country ='GD';
if ($country == 'Guadeloupe') $country ='GP';
if ($country == 'Guam') $country ='GU';
if ($country == 'Guatemala') $country ='GT';
if ($country == 'Guinea') $country ='GN';
if ($country == 'Guinea-Bissau') $country ='GW';
if ($country == 'Guyana') $country ='GY';
if ($country == 'Haiti') $country ='HT';
if ($country == 'Holy See (Vatican)') $country ='VA';
if ($country == 'Honduras') $country ='HN';
if ($country == 'Hong Kong') $country ='HK';
if ($country == 'Hungary') $country ='HU';
if ($country == 'Iceland') $country ='IS';
if ($country == 'India') $country ='IN';
if ($country == 'Indonesia') $country ='ID';
if ($country == 'Iran (Islamic Republic of)') $country ='IR';
if ($country == 'Iraq') $country ='IQ';
if ($country == 'Ireland') $country ='IE';
if ($country == 'Israel') $country ='IL';
if ($country == 'Italy') $country ='IT';
if ($country == 'Jamaica') $country ='JM';
if ($country == 'Japan') $country ='JP';
if ($country == 'Jordan') $country ='JO';
if ($country == 'Kazakhstan') $country ='KZ';
if ($country == 'Kenya') $country ='KE';
if ($country == 'Kiribati') $country ='KI';
if ($country == 'Korea') $country ='KP';
if ($country == 'Korea, Republic of') $country ='KR';
if ($country == 'Kuwait') $country ='KW';
if ($country == 'Kyrgyzstan') $country ='KG';
if ($country == 'Lao') $country ='LA';
if ($country == 'Latvia') $country ='LV';
if ($country == 'Lebanon') $country ='LB';
if ($country == 'Lesotho') $country ='LS';
if ($country == 'Liberia') $country ='LR';
if ($country == 'Libyan Arab Jamahiriya') $country ='LY';
if ($country == 'Liechtenstein') $country ='LI';
if ($country == 'Lithuania') $country ='LT';
if ($country == 'Luxembourg') $country ='LU';
if ($country == 'Macau') $country ='MO';
if ($country == 'Macedonia') $country ='MK';
if ($country == 'Madagascar') $country ='MG';
if ($country == 'Malawi') $country ='MW';
if ($country == 'Malaysia') $country ='MY';
if ($country == 'Maldives') $country ='MV';
if ($country == 'Mali') $country ='ML';
if ($country == 'Malta') $country ='MT';
if ($country == 'Marshall Islands') $country ='MH';
if ($country == 'Martinique') $country ='MQ';
if ($country == 'Mauritania') $country ='MR';
if ($country == 'Mauritius') $country ='MU';
if ($country == 'Mayotte') $country ='YT';
if ($country == 'Mexico') $country ='MX';
if ($country == 'Micronesia, Fed. States of') $country ='FM';
if ($country == 'Moldova, Republic of') $country ='MD';
if ($country == 'Monaco') $country ='MC';
if ($country == 'Mongolia') $country ='MN';
if ($country == 'Montenegro') $country ='ME';
if ($country == 'Montserrat') $country ='MS';
if ($country == 'Morocco') $country ='MA';
if ($country == 'Mozambique') $country ='MZ';
if ($country == 'Myanmar') $country ='MM';
if ($country == 'Namibia') $country ='NA';
if ($country == 'Nauru') $country ='NR';
if ($country == 'Nepal') $country ='NP';
if ($country == 'Netherlands') $country ='NL';
if ($country == 'Netherlands Antilles') $country ='AN';
if ($country == 'New Caledonia') $country ='NC';
if ($country == 'New Zealand') $country ='NZ';
if ($country == 'Nicaragua') $country ='NI';
if ($country == 'Niger') $country ='NE';
if ($country == 'Nigeria') $country ='NG';
if ($country == 'Niue') $country ='NU';
if ($country == 'Norfolk Island') $country ='NF';
if ($country == 'Northern Mariana Islands') $country ='MP';
if ($country == 'Norway') $country ='NO';
if ($country == 'Oman') $country ='OM';
if ($country == 'Pakistan') $country ='PK';
if ($country == 'Palau') $country ='PW';
if ($country == 'Palestine') $country ='PS';
if ($country == 'Panama') $country ='PA';
if ($country == 'Papua New Guinea') $country ='PG';
if ($country == 'Paraguay') $country ='PY';
if ($country == 'Peru') $country ='PE';
if ($country == 'Philippines') $country ='PH';
if ($country == 'Pitcairn Island') $country ='PN';
if ($country == 'Poland') $country ='PL';
if ($country == 'Portugal') $country ='PT';
if ($country == 'Puerto Rico') $country ='PR';
if ($country == 'Qata') $country ='QA';
if ($country == 'Réunion') $country ='RE';
if ($country == 'Romania') $country ='RO';
if ($country == 'Russian Federation') $country ='RU';
if ($country == 'Rwanda') $country ='RW';
if ($country == 'Saint Helena') $country ='SH';
if ($country == 'Saint Kitts and Nevis') $country ='KN';
if ($country == 'Saint Lucia') $country ='LC';
if ($country == 'Saint Pierre and Miquelon') $country ='PM';
if ($country == 'Saint Vincent and the Grenadines') $country ='VC';
if ($country == 'Samoa') $country ='WS';
if ($country == 'San Marino') $country ='SM';
if ($country == 'Sao Tome and Principe') $country ='ST';
if ($country == 'Saudi Arabia') $country ='SA';
if ($country == 'Senegal') $country ='SN';
if ($country == 'Serbia') $country ='RS';
if ($country == 'Seychelles') $country ='SC';
if ($country == 'Sierra Leone') $country ='SL';
if ($country == 'Singapore') $country ='SG';
if ($country == 'Slovakia (Slovak Rep.)') $country ='SK';
if ($country == 'Slovenia') $country ='SI';
if ($country == 'Solomon Islands') $country ='SB';
if ($country == 'Somalia') $country ='SO';
if ($country == 'South Africa') $country ='ZA';
if ($country == 'South Georgia and South Sandwich Islands') $country ='GS';
if ($country == 'South Sudan') $country ='SS';
if ($country == 'Spain') $country ='ES';
if ($country == 'Sri Lanka') $country ='LK';
if ($country == 'Sudan') $country ='SD';
if ($country == 'Suriname') $country ='SR';
if ($country == 'Svalbard and Jan Mayen') $country ='SJ';
if ($country == 'Swaziland') $country ='SZ';
if ($country == 'Sweden') $country ='SE';
if ($country == 'Switzerland') $country ='CH';
if ($country == 'Syrian Arab Republic') $country ='SY';
if ($country == 'Taiwan, Republic of China') $country ='TW';
if ($country == 'Tajikistan') $country ='TJ';
if ($country == 'Tanzania') $country ='TZ';
if ($country == 'Thailand') $country ='TH';
if ($country == 'Timor-Leste (East Timor)') $country ='TL';
if ($country == 'Togo') $country ='TG';
if ($country == 'Tokelau') $country ='TK';
if ($country == 'Tonga') $country ='TO';
if ($country == 'Trinidad and Tobago') $country ='TT';
if ($country == 'Tunisia') $country ='TN';
if ($country == 'Turkey') $country ='TR';
if ($country == 'Turkmenistan') $country ='TM';
if ($country == 'Turks and Caicos Islands') $country ='TC';
if ($country == 'Tuvalu') $country ='TV';
if ($country == 'Uganda') $country ='UG';
if ($country == 'Ukraine') $country ='UA';
if ($country == 'United Arab Emirates') $country ='AE';
if ($country == 'United Kingdom') $country ='GB';
if ($country == 'United States') $country ='US';
if ($country == 'Uruguay') $country ='UY';
if ($country == 'Uzbekistan') $country ='UZ';
if ($country == 'Vanuatu') $country ='VU';
if ($country == 'Vatican City State') $country ='VA';
if ($country == 'Venezuela') $country ='VE';
if ($country == 'Viet Nam') $country ='VN';
if ($country == 'Virgin Islands (British)') $country ='VG';
if ($country == 'Virgin Islands (U.S.)') $country ='VI';
if ($country == 'Wallis and Futuna Islands') $country ='WF';
if ($country == 'Western Sahara') $country ='EH';
if ($country == 'Yemen') $country ='YE';
if ($country == 'Zambia') $country ='ZM';
if ($country == 'Zimbabwe') $country ='ZW';

?>